version: '3'

services:
  remote_auth:
    container_name: remote_auth
    build: ./open_auth
    volumes:
      - oauth_volume:/django
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  # This loads the environment variables from the .env file
    ports:
      - "8080:8000" #host port changed to 8080
    networks:
      - nw
    depends_on:
      - postgreDB
    restart: on-failure  # Ensures container restarts if it fails
    
  postgreDB:
    image: postgres:16
    container_name: postgreDB
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /home/ayoub/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - nw
  nginx:
    build: ./nginx  # Ensure this points to your Nginx directory with the Dockerfile and nginx.conf
    ports:
      - "443:443"
    depends_on:
      - remote_auth
    volumes:
      - front_volume:/var/www/front
    networks:
      - nw
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - nw
  xo_game:
    build: ./Xo_Game/xo_game/
    ports:
      - 8001:8001
    depends_on:
      - postgreDB
    networks:
      - nw
volumes:
  postgre_volume:
  front_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nginx/srcs
  oauth_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./open_auth
networks:
  nw:
    driver: bridge