# Generated by Django 4.2.10 on 2024-11-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0009_user_info_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
