# Generated by Django 4.2.10 on 2024-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0010_alter_user_info_firstname_alter_user_info_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='scoor',
            field=models.IntegerField(default=0),
        ),
    ]
